auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: C:/loki/index
    cache_location: C:/loki/cache
  filesystem:
    directory: C:/loki/chunks

limits_config:
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  allow_structured_metadata: false

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h